### ISSUE TITLE
Implement interstitial modal window

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#10]
@mmarol and @rubillionaire 

per @mmarol 's figma file please build/implement modal window: https://www.figma.com/file/EgYlZmYTuWTT9JzsLacQro/Congratulations?node-id=232%3A973

@rubillionaire - so when https://congratulations-v2.risd.systems/ goes live on (I'm going to say 12/11) we'll want it to live at the recently freed-up url: welcome.risd.edu (I'm including @room421 on this ticket as I would imagine he would initiate that when we're ready).

So this modal window would sit on top of the homepage of the site and here are the specific scenarios and corresponding variations we would want to consider:

- When students come to the site from the RISD applicant status portal we would NOT want them to see this interstitial modal window. (Basically if they come from the portal - @mmarol slate is at "https://admissions.risd.edu/" right? - we don't want to pose the question: do you want to go to the portal or go to the welcome site, since they are already choosing to go to the welcome site) (perhaps utilizing logic that would say NOT to launch modal on page loads when they are referred from https://admissions.risd.edu/)?
- We would want to allow for someone to opt to no longer see the modal after visiting the site a couple of times. @mmarol do you think this would be based on someone's IP address and putting in place logic that would trigger a pop-up box overtop of the modal or an obvious option to "X" out of the modal - and that either option would ask if the user would like to no longer see the modal and just always proceed to the welcome.risd.edu homepage from then on ?
- @mmarol were there any other specific instances requiring modal variation that I'm not remembering here?

**Comment by rubillionaire** [comment]
@cmiller02 we can definitely skip the modal when someone is coming from admissions.risd.edu.

as for opting out of seeing the modal, perhaps the "X" could toggle the modal state and its state could be stored in the browsers local storage. while we can find out a user's ip address, there is no place for us to store modal state information alongside this ip address, except for within the browser's local storage. unless we create a web service to help track this data. though IP addresses change based on where the user is browsing from, so perhaps it could be used in tandem with the browsers local storage.

@mmarol if we do want to store the state of the modal, it would be nice for it to be something that can be displayed again once its been dismissed.

**Comment by mmarol** [comment]
@rubillionaire what do you mean by that? Like what is the interaction you're imagining to display it again?

**Comment by rubillionaire** [comment]
@mmarol not sure exactly, but you know how you minimize a window you can find it again to reopen it. could look like a tab that is docked somewhere with text that lets you know you can reopen that modal to reorient yourself. just feels like useful information that may not completely sink in on first read. or if its quickly dismissed, it would be a bummer for it to not be visible.

**Comment by mmarol** [comment]
@rubillionaire mmmm i see what you're saying. I think we're going to include a link to the portal in the nav in the "useful sites" section so i don't know if it's super useful to include that option to reopen the modal. I don't think that's a behavioral expectation of modals generally? Additionally, in phase 2 we were hoping to redesign the homepage to include a section that basically outlines the same thing as the modal.

**Comment by cmiller02** [comment]
and just to get back to your earlier points @rubillionaire - great to hear that we can skip the modal when someone is coming from admissions.risd.edu and the "X" to opt out of the modal is perfect.

**Comment by rubillionaire** [comment]
@cmiller02 @mmarol this is now live on the http://congratulations-v2.risd.systems/

if you dismiss the modal, but want to see it again, open up the javascript console in the developer tools and type `modal.show(true)`, this will force the modal to open. it will continue to now show up after dismissed.

**Comment by mmarol** [comment]
@rubillionaire I'm assuming you're still working on the animations and centering the modal in the window?

**Comment by cmiller02** [comment]
noticed a small typo with the email:
![Screen Shot 2019-12-12 at 9 18 30 AM](https://user-images.githubusercontent.com/14020234/70722595-901a5000-1cc5-11ea-9ec3-16ec8b33b910.png)

**Comment by rubillionaire** [comment]
@mmarol ahh didn't realize these needed to be animated. what did you have in mind?

**Comment by cmiller02** [comment]
Hey @rubillionaire - so if you take a look here you can see the animations for the desktop and mobile versions: https://www.figma.com/proto/EgYlZmYTuWTT9JzsLacQro/Congratulations?node-id=318%3A257&viewport=-873%2C-3590%2C0.5&scaling=min-zoom (I think you'll need to hit "R" to make it run and just advance the slides to get to the mobile view)

**Comment by rubillionaire** [comment]
@cmiller02 oh wow! never knew figma could do that. thanks for sharing.

i add the animation to both the desktop and mobile stars, as well as the help question. let me know how its feeling. its on risd.systems so far: http://congratulations-v2.risd.systems/

cc @mmarol

**Comment by mmarol** [comment]
@rubillionaire would it be possible to include the close animation?

And for mobile can the directions of the sliding in match the animation? I like the idea of the left and right being the choices and the animations sorta matching that.

**Comment by cmiller02** [comment]
Thanks @rubillionaire - I believe that the movement of the shapes and the help question seem right for desktop. Looking good! And thanks for mentioning the close animation and the difference in animation between desktop and mobile @mmarol

**Comment by rubillionaire** [comment]
thanks, @cmiller02 !

@mmarol ahh yeah the arrows working with the animation is a nice touch. i just got so used to thinking of them as "top" and "bottom" that i ended up using those directions as transitions.

i made the animation adjustments. also have the the background transitioning now, like the mockup. 

let me know how things are looking!

**Comment by cmiller02** [comment]
things are looking great @rubillionaire 

@mmarol other than having the carousel paused while the modal is open, are there any other modal adjustments needed? (I'm not seeing any, but you might catch something I don't.)

**Comment by mmarol** [comment]
@rubillionaire animations are looking good. Not sure if this was captured in another issue but the text on top of the hero should look like this. Screenshots of the inspector changes are also attached.
<img width="1792" alt="Screen Shot 2019-12-17 at 15 58 39" src="https://user-images.githubusercontent.com/6997772/71033858-272c4100-20e6-11ea-9a42-2fe7368e65d7.png">
![Screen Shot 2019-12-17 at 15 58 47](https://user-images.githubusercontent.com/6997772/71033859-272c4100-20e6-11ea-8ff9-f83a9304a7a9.png)
![Screen Shot 2019-12-17 at 15 58 53](https://user-images.githubusercontent.com/6997772/71033860-272c4100-20e6-11ea-9c6c-8f768ec7cd5a.png)

**Comment by cmiller02** [comment]
thanks for adding these specifications, @mmarol - I just checked the carousel issue and it looks like we hadn't spelled this out anywhere - think it was only present in your mobile figma view before the modal slid in. Sorry for missing this component in my write ups. I will link to this issue in the carousel issue and mention that this is where homepage carousel overlay text is described.

**Comment by rubillionaire** [comment]
@mmarol thanks for pointing that out, and especially for the screenshots

**Comment by rubillionaire** [comment]
@mmarol are the specs you defined no longer relevant because we are using an SVG instead of plain text?

let me know if there is anything else to sort out for this issue. looks like it might be complete to me.

**Comment by cmiller02** [comment]
I thought the same @rubillionaire - just wanted to check with you both before closing. Are we good to close @mmarol ?

**Comment by mmarol** [comment]
👍
