### ISSUE TITLE
utilize current homepage Grid module to add an audience row to homepage

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#11]
@mmarol 

please use the current Grid module in the "Phase 1 - Home" content type to account for something like this:

![Screen Shot 2019-11-25 at 12 29 57 PM](https://user-images.githubusercontent.com/14020234/69563583-63550180-0f7f-11ea-8ab1-4135618e5c70.png)

![Screen Shot 2019-11-25 at 12 30 11 PM](https://user-images.githubusercontent.com/14020234/69563612-6f40c380-0f7f-11ea-8ddc-ded13e197ba3.png)

**Comment by mmarol** [comment]
@rubillionaire the way I did this in the inspector is by adding a new class `home-module--third` which had
```
flex-basis: 33%;
flex-grow: 1;
```
and then just do a `full`, `third`, `third`, `third` in the CMS to achieve what's below. 

Additionally I added a couple more options for the background color of those boxes, so maybe that would need 4 `Large Button background color` options: white, light, medium, dark.
the colors are `#FFFFFF`, `#FBF5DB`, `#F2DD83`, `#EDC92D`.

![Yellow home new](https://user-images.githubusercontent.com/6997772/70249505-753a5f80-174a-11ea-8ede-8bc21ae471a4.jpg)

**Comment by cmiller02** [comment]
Though I don't think this changes things for Ruben, I just wanted to outline the way we're going to kind of time this as a progression (adding audience buttons as different student types get notified of their acceptance):

So on 12/12 the top of the site would look something like this:
[new mock-up for anu.pdf](https://github.com/risd/risd-congratulations-v2/files/3933984/new.mock-up.for.anu.pdf)

then when BRDD get notified in late march we would change to:
<img width="449" alt="Screen Shot 2019-12-06 at 11 06 34 AM" src="https://user-images.githubusercontent.com/14020234/70356712-01c84900-1843-11ea-85fc-20fe71002c58.png">

and then in April when transfers are notified it would change to:
<img width="647" alt="Screen Shot 2019-12-06 at 11 06 41 AM" src="https://user-images.githubusercontent.com/14020234/70356725-0b51b100-1843-11ea-88d7-1e7af680a18d.png">

**Comment by mmarol** [comment]
@rubillionaire @cmiller02 I think if we just had a "third" width option along with "full" and "half", we could just switch out what we use depending on the time of year.

**Comment by cmiller02** [comment]
yes - and that would work for the above to scenarios, right, because we would have 2 rows each set to a "third" in the first one and 3 rows each set to a "third" in the second? @mmarol what would fill the last third in the first scenario - white space?

**Comment by rubillionaire** [comment]
@mmarol I added the `Third` option to the sizes list, and hooked it up to the flex definition you provided. I also updated the colors, and hooked them up to their corresponding colors. for hover states, i used the dark color for the two lighter buttons, and the white for the two darker buttons. let me know how that works out for you

**Comment by mmarol** [comment]
Looks like the color block styling is broken right now?

<img width="1792" alt="Screen Shot 2019-12-12 at 09 44 06" src="https://user-images.githubusercontent.com/6997772/70721643-f56d4180-1cc3-11ea-945a-11d19a0b4d4b.png">

**Comment by cmiller02** [comment]
Also ordering of rows in mobile isn't right:
![mobile stacking](https://user-images.githubusercontent.com/14020234/70722367-2ac65f00-1cc5-11ea-9b4d-4d765431dc3e.png)

**Comment by cmiller02** [comment]
@mmarol thanks so much for fixing homepage colors and mobile row ordering for us yesterday. Do you think there's anything outstanding here or that @rubillionaire needs to know from you?

**Comment by mmarol** [comment]
@rubillionaire I sorta hardcoded the button classes you had set up. Since the next phase will kinda get rid of some of the current modules, making that CMS editable is probably not worth it at this moment.

**Comment by cmiller02** [comment]
definitely agree - especially with phase 2 homepage changes coming. Going to close this out.
