### ISSUE TITLE
making Supporting Content wysiwyg links not default to open in new tab

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#12]
Hey @rubillionaire I noticed that on https://congratulations-v2.risd.systems/next-steps/for-first-year-students/ (the first item in the Supporting Content content type) the "international student support content" link defaults to opening in a new tab even though I don't have the "open in a new tab" box checked.

Conversely, on: https://congratulations-v2.risd.systems/next-steps/for-families/ in the "Important dates" paragraph the first link in that does NOT default to opening in a new tab. 

Don't know if this has to do with the first link being italics or not - I can do further comparing to try to assist. Thanks!

**Comment by cmiller02** [comment]
oow, looks like I can correct this in the html, though, by changing the a href to start with /next-steps rather than the full url, which was defaulting. This would still be good to fix, as I don't think that everyone who will use the CMS would guess to do this, but please make this your last priority.

**Comment by mmarol** [comment]
We had set it up so that internal links (relative paths starting with /) would open in the same tab and absolute links (starting with http) would open in a new tab because it was inconsistent in the wysiwyg content across the site. I feel like getting everyone to understand that pattern would be a better solution? @rubillionaire what do you think?

**Comment by cmiller02** [comment]
I'm totally happy to stick with this method, I just know that I've explained relative and absolute links to several people several times - but then again, this set up would kind of force people to learn, so maybe that is a good thing. And in this case we're speaking about just the undergrad welcome site, not risd.edu or others, so I'm fine to close this out if you guys are.

**Comment by mmarol** [comment]
it's either that or we add a switch/button alongside every field that is for links. Feels like a lot of extra dev work, but @rubillionaire you would have a better sense of that.

**Comment by rubillionaire** [comment]
@cmiller02 definitely agree with @mmarol on his suggestion to use relative paths when linking to a page on the same site. there is an added benefit that you can see the link on a development domain, or production domain, depending on which you are viewing.

**Comment by cmiller02** [comment]
totally get it - I'm going to close this issue out, as I've filled Lauren in on this practice. Thanks to you both!
