### ISSUE TITLE
Update button styling

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2#13]
Button styles to be updated to look like this:
<img width="1792" alt="Screen Shot 2019-12-05 at 11 21 39" src="https://user-images.githubusercontent.com/6997772/70256525-9a34cf80-1756-11ea-9c44-966a1673290d.png">

Changes are:
```css
padding: .5em .75em;
background-color: #4e4e55;
color: #f1f632; /* on the white blocks or */ color: #fff; /* on the yellow blocks */
font-family: "Gotham SSm A","Gotham SSm B","Helvetica Neue",Helvetica,Arial,sans-serif;
text-transform: uppercase;
font-weight: bold;
```

the svg fill would have to mimic the color property

**Comment by cmiller02** [comment]
@rubillionaire - thanks so much for the button work. Here's my only observation. On the homepage the buttons with yellow text seem to have a small strip of yellow at the bottom of the button (same on https://welcome.risd.edu/next-steps/for-families/) but when I look at https://welcome.risd.edu/next-steps/info-sessions/ the buttons seem to have a slight outline of orange all around the black rectangle. 

@mmarol should all buttons (regardless of where they are and if they have white or yellow text in them) have nothing outside the black rectangle?

**Comment by mmarol** [comment]
@cmiller02 @rubillionaire Correct, the buttons should have no borders.

also can we add
```
padding: .5em .75em;
letter-spacing: 0.05em;
```
to all the buttons?

**Comment by rubillionaire** [comment]
@mmarol there was some additional styling on the calendar that was changing its padding and adding a border. i removed these, and now all buttons should look the same.

**Comment by cmiller02** [comment]
@mmarol fixed button stylings on this page: https://welcome.risd.edu/the-studio-and-beyond/a-closer-look/ yesterday, but otherwise I think that all buttons seemed to be looking good. Any concerns @mmarol ?

**Comment by mmarol** [comment]
@rubillionaire @cmiller02 The arrows on all the buttons should be replaced with the arrow SVGs shared on slack

https://risdmedia.slack.com/archives/C44GPJWQ0/p1576079027001400

**Comment by cmiller02** [comment]
just an fyi - on https://welcome.risd.edu/the-studio-and-beyond/a-closer-look/ for the 4 or 5 images that had a "Link URL" in the cms (that resulted in a button) below the image on the front end, I removed them - since the button text wasn't showing. (This way nothing is currently broken.)

**Comment by rubillionaire** [comment]
@mmarol i used the new geometry that you gave me and updated all of the buttons to use the same arrow.

@cmiller02 i updated the gallery images you mentioned to have legible links.

let me know if there is anything else for this.

**Comment by cmiller02** [comment]
thanks for your work on this @rubillionaire. I went into the .systems CMS and added a Link URL for the "RISD Museum special collections" Universal - Images Gallery item. @mmarol here's how it's displaying on https://congratulations-v2.risd.systems/the-studio-and-beyond/a-closer-look/:

![Screen Shot 2020-01-21 at 10 27 16 AM](https://user-images.githubusercontent.com/14020234/72818353-58de7d80-3c39-11ea-8817-c70190497185.png)

**Comment by mmarol** [comment]
The italics and the button both feel off. Can we just switch it to no italics and just underlined for the ones that link off?

![Screen Shot 2020-01-22 at 13 16 28](https://user-images.githubusercontent.com/6997772/72921577-7f73e580-3d19-11ea-83af-9f2ce04a0d63.png)

**Comment by rubillionaire** [comment]
@mmarol good call. it was a bit heavy for what is effectively a caption. i removed the italics, the background, and just have the 2px underline.

<img width="1266" alt="Screen Shot 2020-01-22 at 2 56 06 PM" src="https://user-images.githubusercontent.com/434737/72929343-a802dc00-3d27-11ea-8c6a-865160e840dc.png">

hows that look?

**Comment by mmarol** [comment]
Can we make even the non-linked text black?

**Comment by rubillionaire** [comment]
@mmarol totally.

<img width="1266" alt="Screen Shot 2020-01-22 at 3 03 53 PM" src="https://user-images.githubusercontent.com/434737/72929774-79393580-3d28-11ea-87b8-b27fb05600be.png">

**Comment by mmarol** [comment]
looks great 👍

**Comment by cmiller02** [comment]
Yay! I like this so much better. (I was hoping I wasn't the only one thinking the bold/italics in the button were looking a bit weird.) And yay for not italicizing the places even when they aren't a link!

**Comment by cmiller02** [comment]
deployed!
