### ISSUE TITLE
Update site colors

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2#14]
The yellow color should be updated across the site to `#EDC92D`
The dark grey should be updated across the site to `#000000`

**Comment by rubillionaire** [comment]
@mmarol just updated the `$pop-color` & `$text-color` sass variables, that should change has been deployed and should have everything set.

**Comment by mmarol** [comment]
@rubillionaire looks like the arrow svgs have not taken on the change from grey to black.

Also sending you new SVGs for the button and nav item arrows via slack since I can't upload SVGs here.

**Comment by cmiller02** [comment]
@rubillionaire - one piece of feedback we got at this mornings DI meeting is that it would be better to use the nav item arrow (that @mmarol mentions above) in place of the arrows we use to represent expandable content. Example pages are:

https://welcome.risd.edu/next-steps/info-sessions/
https://welcome.risd.edu/next-steps/for-families/
https://welcome.risd.edu/after-risd/alumni-at-work/

So it would be these content types that utilize the arrow that we would want to swap out.
Universal - Calendar Items
Universal - Alumni Bios

We would, however, like to keep the homepage arrows that point sideways:
![Screen Shot 2019-12-11 at 12 10 38 PM](https://user-images.githubusercontent.com/14020234/70643613-50912c80-1c0f-11ea-9122-565de58573ac.png)

**Comment by mmarol** [comment]
Oh no I think not the arrows, but the carets. I think people didn't realize those meant that the accordion items were expandable.

<img width="133" alt="Screen Shot 2019-12-11 at 13 34 48" src="https://user-images.githubusercontent.com/6997772/70649391-0746da00-1c1b-11ea-90ef-b23f3490f65e.png">

**Comment by cmiller02** [comment]
so sorry to be confusing there - yes, please see @mmarol 's screenshot above.

**Comment by rubillionaire** [comment]
@cmiller02 @mmarol i thought i followed this when i first read it, but can you clarify which arrows you want in which context?

**Comment by cmiller02** [comment]
Sorry @rubillionaire - in place of these arrows:

<img width="37" alt="Screen Shot 2019-12-11 at 9 08 21 PM" src="https://user-images.githubusercontent.com/14020234/70676527-7394fe00-1c5a-11ea-865b-97083ee18428.png">

which are featured on these pages

https://welcome.risd.edu/next-steps/info-sessions/
https://welcome.risd.edu/next-steps/for-families/
https://welcome.risd.edu/after-risd/alumni-at-work/

and these content types:
Universal - Calendar Items
Universal - Alumni Bios

can we instead use this symbol:
<img width="27" alt="Screen Shot 2019-12-11 at 9 08 36 PM" src="https://user-images.githubusercontent.com/14020234/70676567-a2ab6f80-1c5a-11ea-9b8f-bfe0f77ed8fc.png">

but we would like to keep the homepage arrows that point sideways:
<img width="46" alt="Screen Shot 2019-12-11 at 9 11 48 PM" src="https://user-images.githubusercontent.com/14020234/70676663-e605de00-1c5a-11ea-8571-77345168c6ee.png">

hope I'm making sense this time :)

**Comment by cmiller02** [comment]
I think that all that's left for @rubillionaire to do in this issue is directly above, right @mmarol ?

**Comment by mmarol** [comment]
Yeah I think that's it on this issue.

**Comment by cmiller02** [comment]
👍 closing out now

**Comment by cmiller02** [comment]
Sorry to have mistakenly closed this. @rubillionaire - please see my comment from 5 days ago.

**Comment by rubillionaire** [comment]
@cmiller02 that totally makes sense. thanks for the clarification! i have updated these lists to use the same arrow that is used in the nav.

**Comment by cmiller02** [comment]
This is perfect! Thanks so much @rubillionaire - will close out the issue now.
