### ISSUE TITLE
Homepage carousel

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2#15]
This is lower priority, but making an editable image carousel on the homepage hero would be great.

We would want it to pause when the modal is active because it felt distracting in the prototypes (https://www.figma.com/proto/EgYlZmYTuWTT9JzsLacQro/Congratulations?node-id=318%3A257&viewport=243%2C-1366%2C0.25&scaling=min-zoom)

If the pausing thing is too complicated for the timeframe, a quick and dirty option would be to just have a bg image on the modal, with would be 100% width and height. So the carousel would continue playing behind the modal but would just be hidden/covered by a static image.

**Comment by cmiller02** [comment]
and @rubillionaire I didn't know if you had access to this: https://www.dropbox.com/home/Media%20Team/WORKING/Congratulations%20%2B%20Slate/ASSETS/Hero%20images/Selects dropbox link of the 10 carousel images (not sure if you're part of Media Group in the dropbox sharing), so I also sent access to this "Selects" folder to your email.

**Comment by rubillionaire** [comment]
@cmiller02 thanks for the link! just verified i've got access

question, do you or @mmarol remember which site i put a hero carousel in for semi-recently? i was happy that it used responsive images and could be toggled on or off, so it felt like it would be a good piece to reuse here. 

never mind about the carousel, it was for risd weekend, i just didn't see it being used and had to find it in the templates!

**Comment by cmiller02** [comment]
@rubillionaire - yes, good thought. Sorry - I just took it out of the CMS last week, but so glad that you found it.

**Comment by cmiller02** [comment]
note: specifics on the homepage text that sits on top of the carousel can be found in the following issue: https://github.com/risd/risd-congratulations-v2/issues/10

**Comment by rubillionaire** [comment]
there is a first version of the homepage carousel on http://congratulations-v2.risd.systems/

when the modal is showing the carousel pauses, and once dismissed there is a short pause (500ms) before going into the carousel which switches images ever 1500ms. these were the values that we used for risd weekend, so i thought that would be a good starting point.

let me know what you think!

thanks for the note about the text. i'll make those updates.

**Comment by rubillionaire** [comment]
@mmarol i used the screenshots you uploaded to extrapolate sizes across different screen widths. check'em out on http://congratulations-v2.risd.systems/ and let me know how they look!

**Comment by mmarol** [comment]
@rubillionaire can we add this drop-shadow to the `.home__hero-text`?
`filter: drop-shadow(5px 5px 5px #00000070);`

seeing the scale relationships shifting with window size, I'm wondering if it would be better to just use an SVG

**Comment by rubillionaire** [comment]
@mmarol you want me to drop that in to `.home__hero-text` in addition to the drop shadows on the svg and the `caption`?

i could definitely see going with all SVG or all type for the hero. the small bummer about going with SVG is that we'd the smaller one to include the line break. but if you want to cut 2 SVGs for me, i could drop them in place of the SVG + text that we have now, which i agree, is a little odd because they scale based on different properties.

**Comment by mmarol** [comment]
@rubillionaire I've added the SVGs to this folder.
https://www.dropbox.com/sh/2aegzf0ugor9w5t/AABwpSzWKagWwSaNapx6HEG8a?dl=0

`Header lockup desktop` and `mobile`

**Comment by rubillionaire** [comment]
@mmarol i've updated the home page to use the SVGs you provided, instead of the text from the CMS and separate RISD wordmark SVG.

https://congratulations-v2.risd.systems/

i started with 2rem padding on the left and right side. so its full width minus those 4rem of padding.

let me know how it looks to you.

**Comment by cmiller02** [comment]
thanks @rubillionaire! @mmarol how do you think the padding is looking are we good as is?

**Comment by mmarol** [comment]
+1

**Comment by mmarol** [comment]
👍

**Comment by cmiller02** [comment]
deployed!
