### ISSUE TITLE
Correct fonts on typography.com?

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#16]
@mmarol can I ask that you please check that all the correct fonts are in the Undergrad Welcome production project at typography.com (and remove any we aren't using). Thanks so much.

**Comment by mmarol** [comment]
@rubillionaire can you confirm what fonts are being used on the site?

**Comment by rubillionaire** [comment]
@mmarol we are using the undergrad welcome project on typography.com, which has the following typefaces

<img width="1320" alt="Screen Shot 2019-12-11 at 12 18 39 PM" src="https://user-images.githubusercontent.com/434737/70644168-766b0100-1c10-11ea-97f3-e30e9cb8ef36.png">

**Comment by mmarol** [comment]
Oh sorry I meant in the code, so that I could remove any that we weren't using. Like Mercury Text Grade 1 shouldn't be in use if we're using ScreenSmart.

**Comment by rubillionaire** [comment]
@mmarol ahh okay. the two bits that are used to define our serif and sans-serif options are here:

https://github.com/risd/risd-congratulations-v2/blob/develop/scss/dependencies/_type.scss#L7-L13

those are the only ones used throughout the site.

**Comment by mmarol** [comment]
@rubillionaire 
can we change
```sass
%serif {
  font-family: "Mercury Text G1 A", "Mercury Text G1 B", "Georgia", "Times New Roman", "Times", serif;
}
```
to
```sass
%serif {
  font-family: "Mercury SSm A", "Mercury SSm B", "Georgia", "Times New Roman", "Times", serif;
```

and then I can get risd of the Mercury text.

**Comment by rubillionaire** [comment]
@mmarol i made the update.

**Comment by mmarol** [comment]
@rubillionaire I've republished the fonts with the updates. Can you replace the font folder in the repo with this folder?
https://www.dropbox.com/s/djsyrgtjs9pyti9/760679.zip?dl=0

<img width="790" alt="Screen Shot 2019-12-12 at 09 50 28" src="https://user-images.githubusercontent.com/6997772/70722197-d91dd480-1cc4-11ea-88c7-593f49e75c63.png">

**Comment by cmiller02** [comment]
@mmarol - is the only thing left for @rubillionaire to do written-up in the comment directly above?

**Comment by mmarol** [comment]
yeah I'll have to confirm it on typography.com once he does that

**Comment by rubillionaire** [comment]
@mmarol i went ahead and uploaded the new font files, and confirmed the change within the cloud dashboard. i thought i might have to change the CSS link but it looks like it uses the same link, so we should be all set.

let me know if there is anything else to take care of.

**Comment by cmiller02** [comment]
thanks @rubillionaire. @mmarol can you now confirm on typography.com?

**Comment by mmarol** [comment]
Seems good to me.
