### ISSUE TITLE
Update type sizes

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2#17]
update the body and list (and anything else like that) type sizes to 20px
and the required symbol text to 15px

and make the max-width 30em instead of 40em

<img width="1792" alt="Screen Shot 2019-12-10 at 15 04 31" src="https://user-images.githubusercontent.com/6997772/70564539-6397f400-1b5e-11ea-8775-c848a5583719.png">

**Comment by rubillionaire** [comment]
@mmarol i went ahead and updated the `serif-m` size, which corresponds to the type you wanted to update. it now sits at 20px with a line height of 28 (i just used the same ratio was was there before). the required symbol is up to 15px.

**Comment by cmiller02** [comment]
Just wondering @mmarol / @rubillionaire  if, on mobile, the headers for these Supporting Content modules should be larger. (See "Total costs" below):

![Screenshot_20191213-110522](https://user-images.githubusercontent.com/14020234/70814080-be1c9480-1d98-11ea-8e6b-e5e9b0e13d7c.png)

**Comment by mmarol** [comment]
@rubillionaire if those headings could match the 20px type size of the intro block that would be great.

**Comment by cmiller02** [comment]
thanks for your above spec @mmarol

**Comment by rubillionaire** [comment]
@mmarol @cmiller02 the type size of those headings now matches the intro block type size.

let me know if there is anything else to do for this issue.

**Comment by cmiller02** [comment]
yay! this looks great @rubillionaire! @mmarol - we ok for Ruben to push this to the live site?

**Comment by mmarol** [comment]
@cmiller02 Looks good to me

**Comment by cmiller02** [comment]
deployed!
