### ISSUE TITLE
Clone site again

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#18]
@rubillionaire can you please clone https://welcome.risd.edu/ for us again? We're into Phase 2 of this site project now and we'll have a lot of new pages being added, some coming down, etc. so it would be wonderful to have a clone so that the live site could remain as is and we could work with pages that aren't needing to be in draft form. Thanks!

**Comment by rubillionaire** [comment]
hey, @cmiller02

i have duplicated welcome.risd.systems under https://welcome-ph2.risd.systems

im happy to change that URL, if there is something that would read better.

feel free to add more people to the site as you see fit here https://welcome-ph2.risd.systems/cms/#/wh/settings/team

the repository is here https://github.com/risd/risd-congratulations-v2-ph2

@mmarol if you find yourself needing to run a local version, you can do the following

1. clone the repo
2. run `npm install`
3. run `npm run configuration`
4. run `npm start` as usual to get the development build process started. this just a shortcut for `npm run develop`, which is a shortcut for `npx grunt --force`.

**Comment by mmarol** [comment]
thanks 👍

**Comment by cmiller02** [comment]
all seems great, @rubillionaire - thank you! I'm going to close this issue out.
