### ISSUE TITLE
Add styling to Supporting Content content type

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#19]
@rubillionaire - can you please adjust the Supporting Content module so that it will display like the Universal - RISD Resources/Offices content type and the Universal - Providence General Info content type.

This would place a yellow line under each Supporting Content row entry, would make any uploaded images sit to the left of the text instead of to the right, and it would require a tweak to the content type's "Title" field so that we could add (if desired/not required) an associated url to make the title field a link. (If we don't enter a url please just dont have the yellow line under it and no hover state.) Here's a screenshot:

![Screen Shot 2020-01-31 at 10 13 30 AM](https://user-images.githubusercontent.com/14020234/73550549-cac17e80-4412-11ea-81e0-f5d1a3ed6c5e.png)

@mmarol - have I forgotten any specifications here?

**Comment by mmarol** [comment]
@cmiller02 nothing else to add!

**Comment by rubillionaire** [comment]
@cmiller02 the updated look for the Supporting Content is now up on the risd.systems domain.

Here is an example without images: http://congratulations-v2.risd.systems/next-steps/for-first-year-students/

and one with: http://congratulations-v2.risd.systems/next-steps/tuition-and-aid/

let me know how that works.

**Comment by cmiller02** [comment]
Cool! Thanks @rubillionaire ! @mmarol how are things looking to you?

**Comment by mmarol** [comment]
@rubillionaire sorry I didn't notice the left padding before. Can we get rid of it?

So have it be this
<img width="955" alt="Screen Shot 2020-02-10 at 16 08 27" src="https://user-images.githubusercontent.com/6997772/74190061-9ecaa800-4c1f-11ea-870b-0fef557c57a1.png">

instead of this
<img width="971" alt="Screen Shot 2020-02-10 at 16 08 59" src="https://user-images.githubusercontent.com/6997772/74190075-aa1dd380-4c1f-11ea-908e-fec403f17fab.png">

**Comment by rubillionaire** [comment]
@mmarol definitely. i updated the style sheet and deployed.

same URLs, now with less padding.

Here is an example without images: http://congratulations-v2.risd.systems/next-steps/for-first-year-students/

and one with: http://congratulations-v2.risd.systems/next-steps/tuition-and-aid/

**Comment by cmiller02** [comment]
Yay! looking so good @rubillionaire ! @mmarol are we good to deploy now?

**Comment by mmarol** [comment]
Looks good!

**Comment by cmiller02** [comment]
awesome! I'll move this into the Ready to deploy column, @rubillionaire. Thanks to you both!

**Comment by rubillionaire** [comment]
awesome. thanks for reviewing @cmiller02 & @mmarol.

we are deployed!

https://welcome.risd.edu/next-steps/for-first-year-students/
https://welcome.risd.edu/next-steps/tuition-and-aid/
