### ISSUE TITLE
Please add Supporting Content content type

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#3]
Please add Supporting Content content type, like on graduatestudy.risd.edu site. BUT, can you make it so the Title field of the supporting content is NOT required. (I could see Lauren sometimes wanting to use it as a continuance/expansion of the top "Description" and just flowing right from that. Here is the content type from the grad site:
![Screen Shot 2019-11-15 at 4 15 19 PM](https://user-images.githubusercontent.com/14020234/68976233-58ea7900-07c3-11ea-9b57-ab80e007471b.png)

Please have this fall right under the top "Description" and before all other "Page contents":
![Screen Shot 2019-11-15 at 4 16 14 PM](https://user-images.githubusercontent.com/14020234/68976227-55ef8880-07c3-11ea-8404-50618f9191bb.png)

**Comment by rubillionaire** [comment]
as i mentioned on slack, the content type is updated with the new `supporting content` repeatable, which renders right after the `description` in the template.

im using the same display as on the grad study site, but with this site's styles applied. let me know if i can make any other changes to this new component.

**Comment by cmiller02** [comment]
all working great, so I'm going to close this out. Thank you!
