### ISSUE TITLE
Removing Universal - Audiences content type and its dependencies

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#4]
@rubillionaire - for this version of the site we aren't going to be filtering things by audience type. So, can you please remove:

![Screen Shot 2019-11-18 at 12 52 53 PM](https://user-images.githubusercontent.com/14020234/69076893-6f324800-0a02-11ea-8cdb-03fae42aae14.png)

Consequently, can we also remove this, which is baked into Pages:

![Screen Shot 2019-11-18 at 12 55 05 PM](https://user-images.githubusercontent.com/14020234/69077048-c0dad280-0a02-11ea-97d9-3b972f7ee829.png)

Can you please also remove any dependencies based on Audience that you can see. An example that I found is, if I switch the above switch off on the "Info Sessions" page I no longer see the two headers that we'd like to have appear to segment the two groups of dates on the page. Here is a screenshot of what the page looks like once I turn the audience switch off:
[FireShot Capture 133 - Info sessions - Next Steps - Welcome New Students - Rhode Island Scho_ - congratulations-v2.risd.systems.pdf](https://github.com/risd/risd-congratulations-v2/files/3859994/FireShot.Capture.133.-.Info.sessions.-.Next.Steps.-.Welcome.New.Students.-.Rhode.Island.Scho_.-.congratulations-v2.risd.systems.pdf)

Please just let me know if you have any questions or if I can assist in any way with this.

**Comment by rubillionaire** [comment]
all traces of the audience content type have been removed. the templates, styles and javascript have been updated to no longer filter content based on audiences.

let me know if everything is functioning as you would expect.

**Comment by cmiller02** [comment]
seems like things are working great - thanks Ruben! I'll go ahead and close this out - please just reopen if needed.
