### ISSUE TITLE
Make the Name field in the Universal-Pages content type display on the front end as a top page title

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#5]
@rubillionaire : so I'm talking about this field and having it translate to displaying a page title on the front end:

![Screen Shot 2019-11-19 at 12 24 27 PM](https://user-images.githubusercontent.com/14020234/69170251-c6e6b700-0ac7-11ea-9f00-04455f3daa62.png)

(for reference we do this in the "Pages" content type of https://graduatestudy.risd.edu)

Jay and Jordan may suggest some tweaks, but Jordan gave me the go ahead to ask you to essentially try my idea - if you look at https://congratulations-v2.risd.systems/next-steps/financing/ do you see how we're using an h2 for "Tools and calculators." Can we basically use this treatment (h2 that would be centered) for a page title that would be first on the page, before the intro ("Description") text. My logical next request is to ask you to make header items, like the current "Tools and calculators" then become h3s. Here are the fields that make these headers:

Universal - Calendar Items Title 1
Universal - Calendar Items Title
Universal - Post-Enrollment Info Title

though I don't know if there is specific styling/sizing currently associated with h3's as when I try them in the inspector they seem to really shoot down in size - I feel like we would want them larger than what it seems an h3 currently produces.

**Comment by rubillionaire** [comment]
@cmiller02 the change is now live.

i added an h2 to the top of each page, unless that page used the stories relationship, which appears to have its own hero image / page title situation associated with it. it looks like the entire "Community" section falls under this category.

i updated the calendar and info modules to use an h3 instead of an h2. though they tend to lead with an h3 within the content that they hold. so i made the title h3 a little bit bigger, using the same type size that is used for the page description. its a small change, but it seems like there is a smooth gradient to this type system, and this way there is a little bit of difference between the section title's h3, and the various content entries h3.

let me know how thats looking.

**Comment by cmiller02** [comment]
@rubillionaire , I definitely see what you mean about the, for example, "Tools and calculators" looking pretty close to the size of the content under it:
![Screen Shot 2019-11-20 at 10 38 18 AM](https://user-images.githubusercontent.com/14020234/69373068-fb49a700-0c70-11ea-8227-b0d323ed52d8.png)

I do think it would be better if the size difference could be more noticeable - like if "Tools and calculators" size could be more like a size between the page title at top and the "RISD Net Price Calculator"
I notice that our h4 is really small, is our h1 really big? I guess I see them as tiers, kind of like could the top page title be an h1, the "Tools and calculators" be an h2 and the "RISD Net Price" be an h3?
(not so much based on the sizes we currently have assigned to the h1, h2, h3, and h4 - but just the concept of them each being a step down from each other - page title, header, content under the header) 

**ruben 12:47 PM**
yeah the h4 is pretty small, i think it makes sense for it to be. our h1 is huge, and with the length of our page titles it was running off screen on basically all screen sizes
i could tone it down, but im also tempted to just keep the single h2 style, and use that for page headings and page breaks
i know there is actually a hierarchical difference between what those two headings mean, but i also think that can be intuited by the fact that you are scrolling down a single page

**ruben 1:04 PM**
here is a break down of the type sizes:
xxl - 110 px
xl  - 64 px
l   - 30 px
m   - 24 px
s   - 14 px
xs  - 11 px
which map onto elements:
h1 - 110 px
h2 - 64 px
h3 - 24 px
h4 - 14 px
p  - 14 px
the calendar section title is set at type size “l” (30 px), just slightly larger than the h3. bumping up its size would bump up a bunch of different type throughout the site:
- pull quotes in the stories
- the page descriptions (as mentioned in the issue)
- “Discover the work of more RISD graduates:” on the Alumni at Work page (http://congratulations-v2.risd.systems/after-risd/alumni-at-work/)
so i wouldn’t want to make a dramatic difference there.
given the scale we have, and not wanting to add yet another layer to it since too many layers can be confusing and less direct, im tempted to stick with that same h2 style (64 px), matching the headline of the page.
though i could also see bringing down the h1 from 110 px, and using that. 110px is just too big. luckily this style is not currently used anywhere on the site, so it wouldn’t have an impact on other parts of the site. (edited) 
**ruben 1:09 PM**
sorry for the perhaps excessive details, but that was helpful for me to see laid out like that, and thought maybe you would be helped by it too.
i have to run to another meeting, but i will be back in a bit. i’ll play with the sizing a bit more and see what feels good
**cmiller02 2:56 PM**
hmmmm, lots to consider for sure - and definitely I love the details. I do see this as getting a bit out of my expertise area and should probably get this question in front of Jordan and Jay. 

@mmarol - when you have the time - can you comment on header sizes?

**Comment by cmiller02** [comment]
feeling that this is also related to sizing of text, because it's a spacing thing, when you guys consider text sizes can you also please consider the spacing between the top ("Description") text and the start of any other content under it:
<img width="1362" alt="Screen Shot 2019-11-22 at 3 26 07 PM" src="https://user-images.githubusercontent.com/14020234/69458132-ac694380-0d3c-11ea-993d-b1c65a69f759.png">

**Comment by mmarol** [comment]
@rubillionaire can those secondary titles get
```
text-transform: uppercase;
letter-spacing: 0.02em;
```
?
<img width="949" alt="Screen Shot 2019-12-05 at 08 57 36" src="https://user-images.githubusercontent.com/6997772/70241791-a2344580-173d-11ea-9c7d-930ae71d3174.png">

**Comment by mmarol** [comment]
With the spacing,
```
padding: 3rem 0 0 0;
margin-bottom: 0;
```
on the `page__description-container` would work

<img width="1792" alt="Screen Shot 2019-12-05 at 09 13 45" src="https://user-images.githubusercontent.com/6997772/70243082-ecb6c180-173f-11ea-9a6a-dec2b52ea755.png">

**Comment by rubillionaire** [comment]
@mmarol updated! it feeling a bit tighter

**Comment by cmiller02** [comment]
I think that the only thing left to do from a spacing stand-point is to create a little more room above the page name across the top right @mmarol:

![Screen Shot 2019-12-13 at 9 33 11 AM](https://user-images.githubusercontent.com/14020234/70807997-bd7e0100-1d8c-11ea-8132-170b7f75e85e.png)

**Comment by mmarol** [comment]
@cmiller02 @rubillionaire yeah so it matches the space below it.

**Comment by rubillionaire** [comment]
@cmiller02 i have updated the spacing above the names to match the spacing below.

let me know if there is anything else to do before closing out this issue.

**Comment by cmiller02** [comment]
thanks @rubillionaire - are we good to go @mmarol:

![Screen Shot 2020-01-21 at 11 02 05 AM](https://user-images.githubusercontent.com/14020234/72820817-90e7bf80-3c3d-11ea-8b2f-4b631fcf0c89.png)

**Comment by mmarol** [comment]
looks good

**Comment by cmiller02** [comment]
deployed!
