### ISSUE TITLE
Creating a "required" symbol for the calendar pages

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#6]
As discussed, @rubillionaire and @mmarol, we need a "required" symbol that can either go at the beginning or end of bulleted items on this page that I currently have marked as "(required)":
https://congratulations-v2.risd.systems/next-steps/for-first-year-students/

@rubillionaire - you and I were talking about the possibility of using a <span> and a drop-down item (allowing us to work within the wysiwyg that is already there, in the "Supporting content" module that we're using for these dates).

**Comment by mmarol** [comment]
@rubillionaire 
if we could add a span at the end of the required list items, the styling would be
```
font-size: 11px;
color: #EDC92D;
font-family: "Gotham SSm A","Gotham SSm B","Helvetica Neue",Helvetica,Arial,sans-serif;
font-weight: bold;
```
(the color is the pop-color)
<img width="697" alt="Screen Shot 2019-12-05 at 10 26 26" src="https://user-images.githubusercontent.com/6997772/70248967-b716d600-1749-11ea-86fa-c70a3dc7b3b0.png">

**Comment by mmarol** [comment]
also changed the padding to
`padding-left: 1em;` instead of the `1.5em`

**Comment by rubillionaire** [comment]
there is now a `Required symbol` in the text style drop down:

<img width="1320" alt="Screen Shot 2019-12-06 at 3 30 03 PM" src="https://user-images.githubusercontent.com/434737/70363606-e4dd4700-183d-11ea-94b4-9bd8ba83b2c5.png">

it produces the following:

<img width="1320" alt="Screen Shot 2019-12-06 at 3 30 33 PM" src="https://user-images.githubusercontent.com/434737/70363613-edce1880-183d-11ea-9f6b-728a6bae4842.png">

I added an example to the "For first year students" page: http://congratulations-v2.risd.systems/next-steps/for-first-year-students/

**Comment by cmiller02** [comment]
I think we're good on this issue, right @mmarol ?

**Comment by mmarol** [comment]
Well it seemed to have reset itself yesterday so I'm worried about that happening again.
@rubillionaire it seemed like all the spans that were applied just disappeared and had to be re-applied.

**Comment by cmiller02** [comment]
good point, @mmarol - I think I blocked out a lot of what we went through yesterday. Yes-this functionality staying constant is important. At other times I've noticed that I can't type an uppercase "R", highlight it, and then select "Required symbol" from the drop down - instead I have to go to the dropdown first, click "Required symbol" and then type an "R" - just to note.

**Comment by rubillionaire** [comment]
@mmarol @cmiller02  i haven't been able to reliably recreate the scenario you describe about spans disappearing. i went through the wysiwyg options and found there is one that will remove span's without attributes when the wysiwyg content is loaded. perhaps this will stop them from being removed.

if you notice any patterns about when this happens let me know.

**Comment by cmiller02** [comment]
Thanks @rubillionaire and @mmarol. I'll close this for now - can reopen if we see this crop up again.
