### ISSUE TITLE
Indication of link missing

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#7]
@rubillionaire and @mmarol - I had mentioned this to you guys briefly when I talked to each of you in the work room the other week about some of the design/dev needs for the site. For these content types:

Universal - Orientation Programs
Universal - Providence General Info
Universal - RISD Resources/Offices

there currently is no indication that the header of items is a link. Here is an example from the "Exploring Providence" page:

![Screen Shot 2019-11-25 at 10 54 46 AM](https://user-images.githubusercontent.com/14020234/69556270-74e3dc80-0f72-11ea-9029-3e6578e9a3cd.png)

@mmarol - would you want Ruben to implement a yellow line underneath the headers of these content types, like we do here when words in a page's "Description" text are links:
![Screen Shot 2019-11-25 at 10 59 43 AM](https://user-images.githubusercontent.com/14020234/69556884-972a2a00-0f73-11ea-89ba-6c0515837bd8.png)
I realize that these aren't headers, but wasn't sure if you'd apply this same style or if you could otherwise indicate what you'd like @rubillionaire to put in place.

**Comment by mmarol** [comment]
looks like the bottom border on those links were disabled in the previous design.
We can just turn them back on.
@rubillionaire I think the borders across the site can be bumped up to 2px instead of 1px.
<img width="1792" alt="Screen Shot 2019-12-05 at 10 30 02" src="https://user-images.githubusercontent.com/6997772/70249392-589e2780-174a-11ea-91d3-696b2f8e693d.png">

**Comment by rubillionaire** [comment]
@cmiller02 the link under line has been restored for these components.

@mmarol i bumped the border bottom to 2px from 1px.

**Comment by cmiller02** [comment]
@rubillionaire - on a related note, in these content types:

Universal - Providence General Info
Universal - Orientation Programs

we have link url fields:

![Screen Shot 2019-12-13 at 10 16 52 AM](https://user-images.githubusercontent.com/14020234/70810437-befdf800-1d91-11ea-96c2-e2693068a099.png)

that, when a relative url is put in, a new tab still opens up. @rubillionaire can you adjust these fields, in both of these content types, to follow the relative url = same tab, absolute url = new tab logic.

Actually the Universal - RISD Resources/Offices content type could be tweaked the same way. (Right now we are only using it to link people to outside sites, but it would be good for this functionality to work the same there in case we needed to link internally using this content type in the future.)

**Comment by rubillionaire** [comment]
@cmiller02 i went through and updated all links to open up in the same tab if they are within the site, and to open up in a new tab if they are external links.

let me know how this is working for you, and if there is anything else to take care of for this issue.

**Comment by cmiller02** [comment]
thanks @rubillionaire - the link/tab work you did seems to be working great. @mmarol if you're good with the 2px border bottom that Ruben set I think we can go ahead and push these changes.

**Comment by mmarol** [comment]
If all the lines across the site could be switched to 2px that would be great (like the divider line)
![Screen Shot 2020-01-21 at 13 12 30](https://user-images.githubusercontent.com/6997772/72830894-b54c9780-3c4f-11ea-873d-bf1e85a2159e.png)

**Comment by rubillionaire** [comment]
@mmarol just pushed a change that bumps all line widths to 2px

**Comment by mmarol** [comment]
looks good

**Comment by cmiller02** [comment]
deployed!
