### ISSUE TITLE
implementation of collapsed navigation

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#8]
![Screen Shot 2019-11-25 at 11 17 53 AM](https://user-images.githubusercontent.com/14020234/69557863-4adfe980-0f75-11ea-82d2-f20e4ae81151.png)

per @mmarol's figma file: https://www.figma.com/file/EgYlZmYTuWTT9JzsLacQro/Congratulations?node-id=0%3A1

**Comment by rubillionaire** [comment]
thanks @cmiller02.

@mmarol thanks for the mock ups. i imagine we will want to use the sections as nav headings, and individual pages listed under their section heading?

**Comment by mmarol** [comment]
@rubillionaire yes sections and nested individual pages would be great. An additional section at the end called "useful sites" or something would be great as well for links to the Slate portal and any other sites we think would be good to include.

**Comment by mmarol** [comment]
Also here are mockups of the nav
![Screen Shot 2019-12-05 at 13 22 17](https://user-images.githubusercontent.com/6997772/70263586-b6d80400-1764-11ea-8eea-0e81ce9b65e8.png)
![Screen Shot 2019-12-05 at 13 38 30](https://user-images.githubusercontent.com/6997772/70263587-b6d80400-1764-11ea-9450-4d543586e69e.png)

**Comment by mmarol** [comment]
Was chatting with Jordan and I think we should move towards removing the "Welcome" from the bar. It feels redundant and doesn't really add anything.

**Comment by cmiller02** [comment]
that sounds great. don't think it's accomplishing anything and with the same exact word it does seem a little silly. thanks!

**Comment by rubillionaire** [comment]
@mmarol i put up a first cut of this.

i used modern pictograms for the toggle arrow, though it looks like it has a different angle than the one you used in your mock-up.

@cmiller02 there are new "Useful Links" fields in both the "Phase 1" and "Phase 2 - Primary Nav" content types that can be used to modify the list of links included at the end of the nav. removing all rows from the "Useful Links" repeatable will remove the heading and any other links that were below it.

let me know how its feeling to you.

**Comment by cmiller02** [comment]
really looking good @rubillionaire ! Thank you! Quick question - @mmarol by removing "Welcome" from the center of the collapsed nav bar did we eliminate our way to get back to the homepage? (I don't think we currently have a way to get home.)

**Comment by mmarol** [comment]
We could have a home navigation item in the nav list

**Comment by cmiller02** [comment]
Sure - seems like a logical solution to me. So just "HOME" as the first item, above this:
 
![Screen Shot 2019-12-10 at 10 50 39 AM](https://user-images.githubusercontent.com/14020234/70545039-f888f600-1b3a-11ea-877c-94423902ed5b.png)

right?

**Comment by mmarol** [comment]
yes

**Comment by cmiller02** [comment]
Thanks @mmarol. Please proceed with adding "HOME" as the first item in the nav @rubillionaire.

**Comment by rubillionaire** [comment]
@cmiller02 good catch! i added the "HOME" link to the top of the nav, so there is a way to find the home page once again.

**Comment by cmiller02** [comment]
things are looking really good @rubillionaire ! Here are my only questions:
- @mmarol do you want @rubillionaire to ONLY all caps the "USEFUL LINKS" and follow your mock-up for the sections (first letter capital)?
- @mmarol are you good with the toggle arrows that Ruben put in?

**Comment by mmarol** [comment]
Can we make everything (except "USEFUL LINKS") Sentence case instead of ALL CAPS?

Also that lack of space between "the studio and beyond" and the toggle is too tight.

<img width="256" alt="Screen Shot 2019-12-11 at 09 10 18" src="https://user-images.githubusercontent.com/6997772/70628383-123b4380-1bf6-11ea-9495-6b973d21131f.png">

**Comment by rubillionaire** [comment]
@mmarol everything is set to sentence case except the useful links heading, and i added a max width to the spans so that they dont get too close to the icons. although i didn't see them as close as your screenshot shows, so let me know if the new styles are helpful

**Comment by mmarol** [comment]
@rubillionaire looks good!

Will changing the `overflow-y: scroll;` to `auto` mess things up? that scrollbar feels a little redundant when you can't scroll

**Comment by cmiller02** [comment]
one very tiny thing @rubillionaire - can you please extend the link tags in the USEFUL LINKS (in the hamburger) to include the arrows:
![Screen Shot 2019-12-13 at 10 28 01 AM](https://user-images.githubusercontent.com/14020234/70811319-5dd72400-1d93-11ea-8c4a-be4dcdd8e9b0.png)

so that they are clickable as well, just like the words next to them are. So basically, for example, everything here would be clickable:
![Screen Shot 2019-12-13 at 10 29 36 AM](https://user-images.githubusercontent.com/14020234/70811409-8d862c00-1d93-11ea-918d-6290c89b1851.png)

oh and @mmarol - did we want to proceed, as you'd mentioned yesterday, with putting the centered "Welcome" back in the nav bar to enable people to go home?

**Comment by mmarol** [comment]
@cmiller02 @rubillionaire oh yeah that would be great. I thought the Home in the sidenav would be enough but I keep finding that I want to click the bar to go home.

**Comment by rubillionaire** [comment]
@cmiller02 i have updated the Useful Links section to include the arrow as part of the clickable URL.
I also added the "Welcome" link to the middle of the site header that will take you back to the homepage. definitely feels a little more complete with that shortcut there.

**Comment by mmarol** [comment]
@rubillionaire seeing this overlap on the arrow
![Screen Shot 2020-01-21 at 11 08 38](https://user-images.githubusercontent.com/6997772/72821352-66e2cd00-3c3e-11ea-8eb9-2f43f43d93af.png)

**Comment by rubillionaire** [comment]
@mmarol oh weird. i wasn't seeing any over lap until going below the width of the nav (~320px). i went ahead and added a width of 90% on the text, so it shouldn't overlap with the arrow. if you are still seeing it, let me know what screen width you are working against and i'll see what i can do.

**Comment by cmiller02** [comment]
it's looking good to me, at varied screen width's @rubillionaire - but I'll leave it to @mmarol to confirm. Thanks!

**Comment by mmarol** [comment]
looks good to me

**Comment by cmiller02** [comment]
deployed!
