### ISSUE TITLE
swapping out footer

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#9]
@rubillionaire - can you please swap out the footer that's currently on https://congratulations-v2.risd.systems/ with the following from @mmarol 's figma file:

![Screen Shot 2019-11-25 at 11 33 21 AM](https://user-images.githubusercontent.com/14020234/69559467-00ac3780-0f78-11ea-8f7d-8c6ad7f111d2.png)

The top grey sitemap section could function just like what we currently use to create the sitemap portion of the current footer. Here it is in the CMS:
![Screen Shot 2019-11-25 at 11 38 28 AM](https://user-images.githubusercontent.com/14020234/69559616-423ce280-0f78-11ea-95e5-e81dcad3afe5.png)

And @mmarol tells me that the bottom (white) section comes directly from the Start Here site. If you could please just ensure that, if you drop the Start Here footer in, that Lauren and I could edit it in the "Universal - Footer" content type that would be great, as we'll need to delete some links and add the welcome@risd.edu email address - but you dropping in the Start Here one should work for our purposes, as long as we can edit the fields.

**Comment by rubillionaire** [comment]
@cmiller02 sounds good. thanks for the image! this site and the start here site use different sets of variables, but I can normalize based on @mmarol's mockup.

**Comment by mmarol** [comment]
@rubillionaire here's a mockup of the footer with colors

![Screen Shot 2019-12-05 at 13 44 38](https://user-images.githubusercontent.com/6997772/70263950-7331ca00-1765-11ea-94bf-9e5eb7c445fd.png)

Using this site's styles makes sense. I think it would just mimic start here structurally

**Comment by cmiller02** [comment]
@mmarol I know that Anu wants the welcome@risd.edu email address to be as prominent in the footer as possible. If @rubillionaire makes the lower portion of the footer editable in the CMS do you foresee us being able to do that well enough or would any additional styling be needed.

**Comment by mmarol** [comment]
Can we maybe replace this social media bar with a link to the email? Is that bar ever used?
I don't think there's going to be a way to really make it more prominent in the footer without making the footer look weird.

<img width="1792" alt="Screen Shot 2019-12-09 at 09 14 33" src="https://user-images.githubusercontent.com/6997772/70442434-572f7080-1a64-11ea-8881-f5ce299bd216.png">

**Comment by cmiller02** [comment]
it's funny - I was originally thinking the same thing but we only use that on the homepage. I like the idea though. Perhaps if it wasn't as large it could remain constant across pages?

**Comment by mmarol** [comment]
the first item on the right-most column of the footer could say something like "more questions? email us at welcome@risd.edu" and then list the request, visit and apply buttons below.

**Comment by cmiller02** [comment]
From Slack conversation:

Carrie:
So I think we don't need the right column of the 3 links, and we don't need the Admissions on facebook link. Lauren and I think we should keep instagram - and maybe add the 1877 FB and twitter to be with the instagram? 

In terms of the far L column we would just do:
Rhode Island School of Design
Two College Street
Providence, RI 02903-2784

If we could please leverage 
![Screen Shot 2019-12-09 at 1 33 58 PM](https://user-images.githubusercontent.com/14020234/70463256-8e187d00-1a8a-11ea-8bff-7cdb13eede6a.png)

for some prominence to the welcome@risd.edu email address that would be great.

Jay Marol:
sure that sounds good
we can get rid of that social media bar and just replace it with a “full” module that links to the email
Carrie Miller:
We don't think there is a need anymore for the https://congratulations-v2.risd.systems/contact/ page anymore, so making the welcome email nice and prominent would be great - awesome! (edited) 
yes!

**Comment by cmiller02** [comment]
So I added a 10th row on the homepage to produce this:
![Screen Shot 2019-12-10 at 12 12 05 PM](https://user-images.githubusercontent.com/14020234/70551882-6129a000-1b46-11ea-883e-32f5a5c48875.png)

but looks like these must be at the template level:
![Screen Shot 2019-12-10 at 12 12 18 PM](https://user-images.githubusercontent.com/14020234/70551901-6be43500-1b46-11ea-8b74-f8d5cfe5a553.png)

Since I cleared out these fields:
![Screen Shot 2019-12-10 at 12 13 22 PM](https://user-images.githubusercontent.com/14020234/70551945-7d2d4180-1b46-11ea-9e3a-7abfdcd503f6.png)

@rubillionaire can you please remove ?

@mmarol I think the 10th row for the email address will work well on the homepage, but I do think that having the email more prominent than just in the footer on all pages would be a good move. (Sorry that I was temporarily forgetting that our full-width row idea for the email address wouldn't address my interior pages concern) Do you have any suggestions for prominence on interior pages or perhaps in the hamburger - but not sure if that's best practice

**Comment by mmarol** [comment]
Can we have it in the nav instead in the Useful links section? My initial suggestion was to make it take up the right most column of the footer.

**Comment by cmiller02** [comment]
Yeah, i think that in the nav would be better in terms of visibility. Unless we want to have it in both places?

**Comment by rubillionaire** [comment]
@cmiller02 i removed the markup that was showing the empty button below the social buttons. there is a new repeatable in the Footer content type that can be used to populate social media accounts, they will be listed where the instagram link is currently showing; 3rd column for larger screens, or at the top of the mobile footer.

@mmarol i put up a version of the footer using Start Here as a template. let me know how its feeling.

**Comment by cmiller02** [comment]
@rubillionaire - I think that we're nearly there with the footer in terms of what I'm needing to put in and having it show up. I put in the 3 social media links, as you described, and I edited the Useful links list. I also edited the address area but I think that the first thing "Admissions Office" might be hardcoded. Also, since we don't want to list a phone number, only an email address, I kind of cheated and put the email address in the phone number field so the email would appear where I wanted it to. (Would you mind maybe just re-labeling those fields or whatever is easiet.) Here's what I did in the CMS - so we would want "Rhode Island School of Design" to be the first thing and not see "Admissions Office" at all

<img width="790" alt="Screen Shot 2019-12-10 at 9 52 12 PM" src="https://user-images.githubusercontent.com/14020234/70587232-65ca7480-1b97-11ea-83a6-6f8f66603273.png">

Also, now that we're putting the social links in the footer itself we actually don't need these circular  icons - could you please remove them:

<img width="583" alt="Screen Shot 2019-12-10 at 9 47 14 PM" src="https://user-images.githubusercontent.com/14020234/70587380-c9ed3880-1b97-11ea-8ede-92b7efa82a03.png">

Thanks so much!

**Comment by mmarol** [comment]
@rubillionaire it's generally looking good. Looks like there's some weird spacing issues on larger screens

<img width="1792" alt="Screen Shot 2019-12-11 at 09 03 46" src="https://user-images.githubusercontent.com/6997772/70628037-5d088b80-1bf5-11ea-8d26-3afaf561aca6.png">

**Comment by rubillionaire** [comment]
@mmarol thanks for pointing that out! i had some media queries from the past footer messing with the layout.

@cmiller02  i updated the footer so that the email address can be populated from the correct location. i also updated the CMS so the email address is in that spot, rather than in the phone number field. the large social icons have also been removed. & the "Admissions Office" that was hard coded is now gone.

**Comment by cmiller02** [comment]
thanks for taking care of what I mentioned @rubillionaire !

**Comment by cmiller02** [comment]
I think the only question I have left on this (@mmarol / @rubillionaire) is if we're all good on spacing. It seems to me that the "AFTER RISD" section in the yellow sitemap portion is closer to "THE STUDIO AND BEYOND" section than the other sections are to each other? Though I get that the "THE STUDIO AND BEYOND" is longer from left to right than the others, so not sure:

![Screen Shot 2019-12-13 at 10 45 09 AM](https://user-images.githubusercontent.com/14020234/70812619-f9699400-1d95-11ea-951d-39fb45e0af71.png)

**Comment by mmarol** [comment]
@cmiller02 that's just the nature of equal column widths. 
@rubillionaire One change that would be great is to match the space below the headers to the space between the items.

**Comment by cmiller02** [comment]
totally - got it, thanks @mmarol 

@rubillionaire - I think that all that's left is @mmarol 's request directly above about spacing. Then I think we're set on this.

**Comment by rubillionaire** [comment]
@cmiller02 the spacing below the section titles in the footer is now the same as the spacing between the listed links.

let me know if there is anything else to take care of with this one.

**Comment by mmarol** [comment]
looks good to me

**Comment by cmiller02** [comment]
Just keeping this open till it gets deployed. (@rubillionaire I'll move this to the "Ready to deploy" column)

**Comment by cmiller02** [comment]
deployed!
